
name: todoapp

services:
  command-db:
    build: ../command-db
    volumes:
      - command-db-data:/var/lib/postgresql
  event-db:
    build: ../event-db
    ports:
      - 3000:3000
    volumes:
      - event-db-data:/var/lib/postgresql
  admin:
    build: ../admin
    ports:
      - 4000:4000
    volumes:
      - ../admin/src:/app/src:ro
      - ../admin/public:/app/public:ro
      - ../admin/index.html:/app/index.html:ro

volumes:
  command-db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./command-db
  event-db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./event-db
