
name: todoapp

services:
  event-db:
    build: ../event-db
    ports:
      - 3000:3000
    volumes:
      - ../event-db/src:/app/src:ro
      - event-db-data:/var/lib/postgresql
  object-reducer:
    build: ../object-reducer
    ports:
      - 3001:3000
    volumes:
      - ../object-reducer/src:/app/src:ro
      - object-reducer-data:/var/lib/postgresql
  command-processor:
    build: ../command-processor
    ports:
      - 3002:3000
    environment:
      - EMAIL_HOST_NAME=localhost
    volumes:
      - ./public.pem:/app/public.pem:ro
      - ../command-processor/src:/app/src:ro
  object-broker:
    build: ../object-broker
    volumes:
      - ./private.pem:/app/private.pem:ro
      - ../object-broker/src:/app/src:ro
  elastic-indexer:
    build: ../elastic-indexer
    volumes:
      - ../elastic-indexer/src:/app/src:ro
      - elastic-indexer-data:/mnt
      # environment:
      #   - cluster.routing.allocation.disk.threshold_enabled=false
  automation:
    build: ../automation
    volumes:
      - ../automation/src:/app/src:ro
      - ./private.pem:/app/private.pem:ro
    ports:
      - 3004:3004
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - AUTOMATION_USER_ID=${AUTOMATION_USER_ID}
  admin:
    build: ../admin
    volumes:
      - ../admin/src:/app/src:ro
      - ../admin/public:/app/public:ro
      - ../admin/index.html:/app/index.html:ro
  back-office:
    build: ../back-office
    environment:
      - DEVELOPMENT=1
    volumes:
      - ../back-office/packages/spa/src:/app/packages/spa/src:ro
      - ../back-office/packages/spa/public:/app/packages/spa/public:ro
      - ../back-office/packages/spa/index.html:/app/packages/spa/index.html:ro
  admin-nginx:
    image: nginx
    volumes:
      - ./admin-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 4001:80
  back-office-nginx:
    image: nginx
    volumes:
      - ./back-office-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

volumes:
  event-db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./event-db
  object-reducer-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./object-reducer-db
  elastic-indexer-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./elastic-indexer-data
